name: Convert JSON to XLSX

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci
    - name: Convert JSON to XLSX
      run: npm run start
    - name: Archive .xlsx files
        run: |
          find . -name "*.xlsx" -print | zip archive.zip -@
    - name: Upload archive
      uses: actions/upload-artifact@v3
      with:
        name: archive
        path: ./archive.zip