# .github/workflows/test_action.yaml
name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Converts json file to xslx
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Converting
        id: convert-json-2-xslx
        uses: ./