name: Upload File

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'The name of the file to upload'
        required: true
      path: 
        description: 'The path of the file to upload'
        required: true

jobs:
  upload-file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install curl

      - name: Upload file
        env:
          FILENAME: ${{ github.event.inputs.filename }}
          FILEPATH: ${{ github.event.inputs.path }}
        run: |
          # Fetch the file from an external source
          curl -O "${FILEPATH}/${FILENAME}"
          
          # Commit and push the file to the repository
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "${FILENAME}"
          git commit -m "Add ${FILENAME}"
          git push
